// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOpgjnW1O4HtqejSN2K6s-kr7D7DrdJe0',
    appId: '1:138841801988:web:d880cae1e4c3ccd1bcbc51',
    messagingSenderId: '138841801988',
    projectId: 'yuut-ebrok',
    authDomain: 'yuut-ebrok.firebaseapp.com',
    storageBucket: 'yuut-ebrok.appspot.com',
    measurementId: 'G-JEK9DQFMWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB30_gDNJw8qQR0m9tv-1DiFaJea3r6Db4',
    appId: '1:138841801988:android:d51687ee8b1f4148bcbc51',
    messagingSenderId: '138841801988',
    projectId: 'yuut-ebrok',
    storageBucket: 'yuut-ebrok.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx4_6Cn1HCvGKvGNOFgNwW40rsu8SxviM',
    appId: '1:138841801988:ios:a4859f0b64da8dddbcbc51',
    messagingSenderId: '138841801988',
    projectId: 'yuut-ebrok',
    storageBucket: 'yuut-ebrok.appspot.com',
    iosBundleId: 'com.example.yuutebrok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx4_6Cn1HCvGKvGNOFgNwW40rsu8SxviM',
    appId: '1:138841801988:ios:a4859f0b64da8dddbcbc51',
    messagingSenderId: '138841801988',
    projectId: 'yuut-ebrok',
    storageBucket: 'yuut-ebrok.appspot.com',
    iosBundleId: 'com.example.yuutebrok',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOpgjnW1O4HtqejSN2K6s-kr7D7DrdJe0',
    appId: '1:138841801988:web:af06963cabe580fcbcbc51',
    messagingSenderId: '138841801988',
    projectId: 'yuut-ebrok',
    authDomain: 'yuut-ebrok.firebaseapp.com',
    storageBucket: 'yuut-ebrok.appspot.com',
    measurementId: 'G-J0MQ0WCNGF',
  );
}
